In [3]:
from keras import layers
from keras.models import Model
import keras
import numpy as np

init = keras.initializers.RandomNormal(seed=1)
inp = layers.Input((5, 1))
out1 = layers.GRU(3, return_sequences=True, kernel_initializer=init, recurrent_initializer=init)(inp)
out2= layers.GRU(3, return_sequences=False, kernel_initializer=init, recurrent_initializer=init)(inp)
m1 = Model(inp, [out1, out2])

Using TensorFlow backend.
/Users/vanpelt/.pyenv/versions/3.6.4/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/Users/vanpelt/.pyenv/versions/3.6.4/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [4]:
in_data = np.array([0.1,0.2,0.3,0.4,0.5]).reshape((1,5,1))
m1.predict(in_data)

[array([[[ 0.00148446, -0.00529137, -0.001807  ],
         [ 0.00379733, -0.01328251, -0.00453949],
         [ 0.00656812, -0.02265439, -0.00774633],
         [ 0.00958988, -0.03273204, -0.01119637],
         [ 0.01274805, -0.04316805, -0.014771  ]]], dtype=float32),
 array([[ 0.01274805, -0.04316805, -0.014771  ]], dtype=float32)]

In [19]:
m2 = Model(inp, out2)
m2.compile(loss="mse", optimizer="adam")
m2.fit(in_data, np.array([0.6,0.7,0.8]).reshape((1,3)), epochs=100)

Epoch 1/100
1/1 [==============================] - 1s 893ms/step - loss: 4.8180e-08
Epoch 2/100
1/1 [==============================] - 0s 6ms/step - loss: 7.0771e-07
Epoch 3/100
1/1 [==============================] - 0s 7ms/step - loss: 1.6701e-06
Epoch 4/100
1/1 [==============================] - 0s 7ms/step - loss: 3.3612e-07
Epoch 5/100
1/1 [==============================] - 0s 8ms/step - loss: 2.5461e-07
Epoch 6/100
1/1 [==============================] - 0s 6ms/step - loss: 8.8923e-07
Epoch 7/100
1/1 [==============================] - 0s 5ms/step - loss: 6.6962e-07
Epoch 8/100
1/1 [==============================] - 0s 5ms/step - loss: 4.6714e-07
Epoch 9/100
1/1 [==============================] - 0s 13ms/step - loss: 4.1562e-07
Epoch 10/100
1/1 [==============================] - 0s 8ms/step - loss: 2.3144e-07
Epoch 11/100
1/1 [==============================] - 0s 7ms/step - loss: 1.5412e-07
Epoch 12/100
1/1 [==============================] - 0s 7ms/step - loss: 3.1293e-07
Epoch 13/1

In [20]:
m2.predict(in_data)

array([[0.6000006 , 0.70000726, 0.8000034 ]], dtype=float32)

In [21]:
m2.predict(np.array([0.4,0.5,0.6,0.7,0.8]).reshape((1,5,1)))

array([[0.6888099, 0.7770717, 0.871939 ]], dtype=float32)